name: CI and CD
on:
  push:
    branches:
      - master

permissions:
  contents: write
  
jobs:
  build-and-deploy:
    name: Build and Deploy
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: clean cache
        run: npm cache clean --force

      - name: install npm packages    
        run: npm ci

      - name: build project
        run: npm run build

      - name: tests
        run: npm run test

      - name: Deploy
        uses: actions/deploy-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET }}
